pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Jitpack'
            url = 'https://jitpack.io'
        }
        maven {
            name = 'Babric'
            url = 'https://maven.glass-launcher.net/babric'
        }
        maven {
            name = 'SignalumMavenInfrastructure'
            url = 'https://maven.thesignalumproject.net/infrastructure'
        }
    }
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '2.1.20'
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

// catalyst
include(":catalyst-all")
include(":catalyst-core")
include(":catalyst-fluids")
include(":catalyst-multiblocks")
include(":catalyst-energy")
include(":catalyst-multipart")
include(":catalyst-effects")
// catalyst

include(":tmb")
//include(":btwaila")
//include(":dragonfly")
//include(":vintage-questing")
include(":retrostorage")
//include(":halplibe")
//include(":cc")
//include(":vm")
//include(":ee")
//include(":minimap")

// catalyst
project(":catalyst-all").projectDir = file("${rootProject.projectDir}/../catalyst")
project(":catalyst-core").projectDir = file("${rootProject.projectDir}/../catalyst/core")
project(":catalyst-fluids").projectDir = file("${rootProject.projectDir}/../catalyst/fluids")
project(":catalyst-multiblocks").projectDir = file("${rootProject.projectDir}/../catalyst/multiblocks")
project(":catalyst-energy").projectDir = file("${rootProject.projectDir}/../catalyst/energy")
project(":catalyst-multipart").projectDir = file("${rootProject.projectDir}/../catalyst/multipart")
project(":catalyst-effects").projectDir = file("${rootProject.projectDir}/../catalyst/effects")
// catalyst

project(":tmb").projectDir = file("${rootProject.projectDir}/../tmb")
//project(":btwaila").projectDir = file("${rootProject.projectDir}/../btwaila")
//project(":dragonfly").projectDir = file("${rootProject.projectDir}/../dragonfly")
//project(":vintage-questing").projectDir = file("${rootProject.projectDir}/../vintage-questing")
project(":retrostorage").projectDir = file("${rootProject.projectDir}/../retrostorage")
//project(":halplibe").projectDir = file("${rootProject.projectDir}/../bta-halplibe")
//project(":cc").projectDir = file("${rootProject.projectDir}/../computercraft")
//project(":vm").projectDir = file("${rootProject.projectDir}/../vm")
//project(":ee").projectDir = file("${rootProject.projectDir}/../equivalentexchange-bta")
//project(":minimap").projectDir = file("${rootProject.projectDir}/../BTA-Minimap")