pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Jitpack'
            url = 'https://jitpack.io'
        }
        maven {
            name = 'Babric'
            url = 'https://maven.glass-launcher.net/babric'
        }
        maven {
            name = 'SignalumMavenInfrastructure'
            url = 'https://maven.thesignalumproject.net/infrastructure'
        }
    }
}

// catalyst
include(":core")
include(":fluids")
include(":multiblocks")
include(":energy")
// catalyst

include(":tmb")
include(":btwaila")

// catalyst
project(":core").projectDir = file("${rootProject.projectDir}/../catalyst/core")
project(":fluids").projectDir = file("${rootProject.projectDir}/../catalyst/fluids")
project(":multiblocks").projectDir = file("${rootProject.projectDir}/../catalyst/multiblocks")
project(":energy").projectDir = file("${rootProject.projectDir}/../catalyst/energy")
// catalyst

project(":tmb").projectDir = file("${rootProject.projectDir}/../tmb")
project(":btwaila").projectDir = file("${rootProject.projectDir}/../btwaila")